export const SORTING = 'SORTING'
export const TICKETS = 'TICKETS'
export const CHECKBOXES = 'CHECKBOXES'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ERROR = 'SHOW_ERROR'
export const HIDE_ERROR = 'HIDE_ERROR'